fix: login
WARNING: No user is logged in on site re0:zh
pywikibot.exceptions.OtherPageSaveError: Edit to page [[奇夏/图库]] failed:
User "None" does not have required user right "edit"